# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

## HW 1. numpy



In [11]:
import numpy as np

# Task 1

np.random.seed(10)

nums_array = np.random.randint(0, 100, 10)
print(f"Array: {nums_array}")

average = np.mean(nums_array)
median = np.median(nums_array)
std_dev = np.std(nums_array)
print(f"Average: {average}, Median: {median}, Standard deviation: {std_dev}")


nums_array[nums_array % 2 == 0] = 0
print(f"New array: {nums_array}")


Array: [ 9 15 64 28 89 93 29  8 73  0]
Average: 40.8, Median: 28.5, Standard deviation: 33.68026128164685
New array: [ 9 15  0  0 89 93 29  0 73  0]


In [29]:
# Task 2

np.random.seed(10)
nums_array2 = np.random.randint(0, 100, (3, 3))
print("Array:")
print(nums_array2)

print(f"First row: {nums_array2[0]}")

print(f"Last column: {nums_array2[:, -1]}")

print(f"Diagonal: {np.diag(nums_array2)}")

Array:
[[37  0 18]
 [23  3 29]
 [16 84 82]]
First row: [37  0 18]
Last column: [18 29 82]
Diagonal: [37  3 82]


In [45]:
# Task 3
np.random.seed(10)
nums_array3 = np.random.randint(0, 100, (3, 3))
print("Array 2d:")
print(nums_array3)
nums_array4 = np.random.randint(0, 100, 3)
print("Array 1d:")
print(nums_array4)

nums_array3 += nums_array4
print("Array after adding:")
print(nums_array3)

Array 2d:
[[ 9 15 64]
 [28 89 93]
 [29  8 73]]
Array 1d:
[ 0 40 36]
Array after adding:
[[  9  55 100]
 [ 28 129 129]
 [ 29  48 109]]


In [32]:
# Task 4
np.random.seed(10)
nums_array5 = np.random.randint(0, 100, (5,5))
print("Array:")
print(nums_array5)

unique_values = np.unique(nums_array5)
print(f"Unique values: {unique_values}")

test_number = 250

print(f"Rows where sum > {test_number}:")
print(nums_array5[nums_array5.sum(axis=1) > test_number])


Array:
[[ 9 15 64 28 89]
 [93 29  8 73  0]
 [40 36 16 11 54]
 [88 62 33 72 78]
 [49 51 54 77 69]]
Unique values: [ 0  8  9 11 15 16 28 29 33 36 40 49 51 54 62 64 69 72 73 77 78 88 89 93]
Rows where sum > 250:
[[88 62 33 72 78]
 [49 51 54 77 69]]


In [42]:
# Task 5

nums_array6 = np.arange(1, 21)
print(f"Array: {nums_array6}")

nums_array6 = nums_array6.reshape(4, 5)
print("2D array:")
print(nums_array6)

print(f"Shape: {nums_array6.shape}")

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape: (4, 5)


## HW1. pandas

In [48]:
import pandas as pd
import numpy as np

# Task 1

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda', 'Sandra'],
    'Age': [25, 36, 42, 18, 36],
    'Сity': ['New York', 'Paris', 'London', 'Berlin', 'Rome']
}

df = pd.DataFrame(data)
print(f"{df}\n")
# Task 2

np.seed = 10
df['Salary'] = np.random.randint(1000, 5000, len(df))
print(f"{df}\n")

# Task 3
age = 30
df1 = df[df['Age'] > age]
print(f"{df1}\n")

     Name  Age      Сity
0    John   25  New York
1    Anna   36     Paris
2   Peter   42    London
3   Linda   18    Berlin
4  Sandra   36      Rome

     Name  Age      Сity  Salary
0    John   25  New York    3191
1    Anna   36     Paris    1362
2   Peter   42    London    3637
3   Linda   18    Berlin    3616
4  Sandra   36      Rome    4826

     Name  Age    Сity  Salary
1    Anna   36   Paris    1362
2   Peter   42  London    3637
4  Sandra   36    Rome    4826



In [43]:
# Task 4
import pandas as pd
import numpy as np

df2 = pd.read_csv('wine.csv')
print(f"{df2}\n")

     1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3  

In [21]:
# Task 5

print(f"{df2.head()}\n")


   1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29  5.64  1.04  3.92  \
0  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
1  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
2  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
3  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   
4  1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05  2.85   

   1065  
0  1050  
1  1185  
2  1480  
3   735  
4  1450  



In [22]:
# Task 6

print(f"{df2.describe()}\n")


                1       14.23        1.71        2.43        15.6         127  \
count  177.000000  177.000000  177.000000  177.000000  177.000000  177.000000   
mean     1.943503   12.993672    2.339887    2.366158   19.516949   99.587571   
std      0.773991    0.808808    1.119314    0.275080    3.336071   14.174018   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.360000    1.600000    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.870000    2.360000   19.500000   98.000000   
75%      3.000000   13.670000    3.100000    2.560000   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

              2.8        3.06         .28        2.29        5.64        1.04  \
count  177.000000  177.000000  177.000000  177.000000  177.000000  177.000000   
mean     2.292260    2.023446    0.362316    1.586949    5.054802    0.956983   
std      0.626465    0.9986

In [47]:
# Task 7
category_column = 1
unique_values = df2.iloc[:, category_column].unique()
print(f"{unique_values}\n")


[13.2  13.16 14.37 13.24 14.2  14.39 14.06 14.83 13.86 14.1  14.12 13.75
 14.75 14.38 13.63 14.3  13.83 14.19 13.64 12.93 13.71 12.85 13.5  13.05
 13.39 13.3  13.87 14.02 13.73 13.58 13.68 13.76 13.51 13.48 13.28 13.07
 14.22 13.56 13.41 13.88 14.21 13.9  13.94 13.82 13.77 13.74 13.29 13.72
 12.37 12.33 12.64 13.67 12.17 13.11 13.34 12.21 12.29 13.49 12.99 11.96
 11.66 13.03 11.84 12.7  12.   12.72 12.08 12.67 12.16 11.65 11.64 12.69
 11.62 12.47 11.81 12.6  12.34 11.82 12.51 12.42 12.25 12.22 11.61 11.46
 12.52 11.76 11.41 11.03 12.77 11.45 11.56 11.87 12.07 12.43 11.79 12.04
 12.86 12.88 12.81 12.53 12.84 13.36 13.52 13.62 12.87 13.32 13.08 12.79
 13.23 12.58 13.17 13.84 12.45 14.34 12.36 13.69 12.96 13.78 13.45 12.82
 13.4  12.2  14.16 13.27 14.13]

