# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

## HW 1. numpy



In [11]:
import numpy as np

# Task 1

np.random.seed(10)

nums_array = np.random.randint(0, 100, 10)
print(f"Array: {nums_array}")

average = np.mean(nums_array)
median = np.median(nums_array)
std_dev = np.std(nums_array)
print(f"Average: {average}, Median: {median}, Standard deviation: {std_dev}")


nums_array[nums_array % 2 == 0] = 0
print(f"New array: {nums_array}")


Array: [ 9 15 64 28 89 93 29  8 73  0]
Average: 40.8, Median: 28.5, Standard deviation: 33.68026128164685
New array: [ 9 15  0  0 89 93 29  0 73  0]


In [29]:
# Task 2

np.random.seed(10)
nums_array2 = np.random.randint(0, 100, (3, 3))
print("Array:")
print(nums_array2)

print(f"First row: {nums_array2[0]}")

print(f"Last column: {nums_array2[:, -1]}")

print(f"Diagonal: {np.diag(nums_array2)}")

Array:
[[37  0 18]
 [23  3 29]
 [16 84 82]]
First row: [37  0 18]
Last column: [18 29 82]
Diagonal: [37  3 82]


In [45]:
# Task 3
np.random.seed(10)
nums_array3 = np.random.randint(0, 100, (3, 3))
print("Array 2d:")
print(nums_array3)
nums_array4 = np.random.randint(0, 100, 3)
print("Array 1d:")
print(nums_array4)

nums_array3 += nums_array4
print("Array after adding:")
print(nums_array3)

Array 2d:
[[ 9 15 64]
 [28 89 93]
 [29  8 73]]
Array 1d:
[ 0 40 36]
Array after adding:
[[  9  55 100]
 [ 28 129 129]
 [ 29  48 109]]


In [32]:
# Task 4
np.random.seed(10)
nums_array5 = np.random.randint(0, 100, (5,5))
print("Array:")
print(nums_array5)

unique_values = np.unique(nums_array5)
print(f"Unique values: {unique_values}")

test_number = 250

print(f"Rows where sum > {test_number}:")
print(nums_array5[nums_array5.sum(axis=1) > test_number])


Array:
[[ 9 15 64 28 89]
 [93 29  8 73  0]
 [40 36 16 11 54]
 [88 62 33 72 78]
 [49 51 54 77 69]]
Unique values: [ 0  8  9 11 15 16 28 29 33 36 40 49 51 54 62 64 69 72 73 77 78 88 89 93]
Rows where sum > 250:
[[88 62 33 72 78]
 [49 51 54 77 69]]


In [42]:
# Task 5

nums_array6 = np.arange(1, 21)
print(f"Array: {nums_array6}")

nums_array6 = nums_array6.reshape(4, 5)
print("2D array:")
print(nums_array6)

print(f"Shape: {nums_array6.shape}")

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Shape: (4, 5)
