Для успішного виконання домашки використовуйте документацію [NumPy](https://numpy.org/doc/stable/).

Зверніть увагу на такі методи `numpy`:
* *arange*
* *zeros*
* *ones*
* *full*
* *nonzero*
* *eye*
* *random*
* *sort*
* *sum*
* *min*
* *mean*

In [ ]:
import numpy as np

In [4]:
# Завдання 1: Створити масив розміром 3x3 зі значеннями від 0 до 8
# Hints: np.arange

arr1 = np.arange(9).reshape(3, 3)
print(arr1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
# Завдання 2: Створити вектор розміром 10, заповнений нулями
arr2 = np.zeros(10, dtype=int)  # int look better )))
print(arr2)

[0 0 0 0 0 0 0 0 0 0]


In [57]:
# Завдання 3: Створити вектор розміром 10, заповнений одиницями
arr3 = np.ones(10, dtype=int) # int look better )))
print(arr3)

[1 1 1 1 1 1 1 1 1 1]


In [12]:
# Завдання 4: Створити вектор розміром 10, заповнений значеннями 5
# Hints: np.full
arr4 = np.full(10,5)
print(arr4)

[5 5 5 5 5 5 5 5 5 5]


In [14]:
# Завдання 5: Створити вектор з числами від 10 до 49

arr5 = np.arange(10,50)
print(arr5)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
# Завдання 6: Реверсувати порядок елементів вектора з завдання 5
arr6 = np.flip(arr5)
print(arr6)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [18]:
# Завдання 7: Створити 9x9 матрицю зі значеннями від 0 до 80
# Hints: np.arange
arr7 = np.arange(81).reshape(9,9)
print(arr7)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]


In [21]:
# Завдання 8: Знайти індекси ненульових елементів вектора [1,2,0,0,4,0]
# Hints: np.nonzero

arr8 = np.array([1,2,0,0,4,0])
arr8_nonzero = np.nonzero(arr8)
print(arr8_nonzero)


(array([0, 1, 4]),)


In [22]:
# Завдання 9: Створити одиничну матрицю розміром 3x3
# Hints: np.eye
arr9 = np.eye(3,3)
print(arr9)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Завдання 10: Створити випадковий вектор розміром 10 та відсортувати його
np.random.seed(10)
arr10 = np.array(np.random.randint(0, 100, 10))
arr10_sorted = np.sort(arr10)
print(f"Original array: {arr10}")
print(f"Sorted array: {arr10_sorted}")


Original array: [ 9 15 64 28 89 93 29  8 73  0]
Sorted array: [ 0  8  9 15 28 29 64 73 89 93]


In [31]:
# Завдання 11: Створити матрицю 5x5 з випадковими цілими числами в діапазоні від 0 до 10
np.random.seed(10)
arr11 = np.random.randint(0, 10, (5,5))
print(arr11)

[[9 4 0 1 9]
 [0 1 8 9 0]
 [8 6 4 3 0]
 [4 6 8 1 8]
 [4 1 3 6 5]]


In [32]:
# Завдання 12: Обчислити суму всіх елементів матриці з завдання 11
arr11_sum = np.sum(arr11)
print(f"Sum of all elements: {arr11_sum}")


Sum of all elements: 108


In [35]:
# Завдання 13: Знайти найменше значення в кожному рядку матриці з завдання 11
arr11_min_row = np.min(arr11, axis=1)
print(f"Min value in each row: {arr11_min_row}")


Min value in each row: [0 0 0 1 1]


In [36]:
# Завдання 14: Обчислити середнє значення кожного стовпця матриці з завдання 11
arr11_mean_col = np.mean(arr11, axis=0)
print(f"Mean value in each column: {arr11_mean_col}")


Mean value in each column: [5.  3.6 4.6 4.  4.4]


In [45]:
# Завдання 15: Створити випадковий вектор розміром 15 та замінити максимальне значення на -1
# Hints: np.argmax
np.random.seed(10)
arr15 = np.random.randint(0, 100, 15)
print(f"Array: {arr15}")

max_index = np.argmax(arr15)
arr15[max_index] = -1

print(f"Array after: {arr15}")

Array: [ 9 15 64 28 89 93 29  8 73  0 40 36 16 11 54]
Array after: [ 9 15 64 28 89 -1 29  8 73  0 40 36 16 11 54]


In [53]:
# Завдання 16: Перетворити випадковий вектор розміром 10 в матрицю розміром 2x5
np.random.seed(10)
arr16 = np.random.randint(0, 100, 10)
print(f"Vector: {arr16}")
arr16 = arr16.reshape(2,5)
print(f"Matrix: {arr16}")


Vector: [ 9 15 64 28 89 93 29  8 73  0]
Matrix: [[ 9 15 64 28 89]
 [93 29  8 73  0]]


In [54]:
# Завдання 17: Знайти середнє значення елементів матриці з завдання 16
arr16_mean = np.mean(arr16)
print(f"Mean: {arr16_mean}")


Mean: 40.8
